### ISSUE TITLE
游戏加载后视角无法移动

### ISSUE THREAD

**Issue by liuchenhao24** [MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack#4]
进入单人后视角无法移动

**Comment by RisingInIris2017** [comment]
久等了！
这个问题是旧版本的Raw Mouse Input - Blessed Edition模组的bug导致的。
你可以直接更新这个模组到新版本：
https://www.curseforge.com/minecraft/mc-mods/raw-mouse-input-blessed-edition/files/5146147

下次整合包版本更新会预装新版本的这个模组，不再出现这个问题。
感谢你的反馈！
