### ISSUE TITLE
CustomSkinLoader registers as a trojan to windows defender

### ISSUE THREAD

**Issue by Mdbgamer** [MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack#6]
![image](https://github.com/MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack/assets/61175592/ac1039f7-48fb-4333-9149-6cf25a38cf3f)

Not sure what's going on here, but it's probably a good idea to uh... yaknow, probably check that out. :D

**Comment by Lubang-SF** [comment]
I replied to you on curseforge,so I'll keep it short and sweet.This mod is not developed by us, meanwhile we have not heard of this issue before. We'll check the mod again and consider removing it in a later release. You can remove this mod on your own, it won't affect your ability to play the pack at all! I hope this helps.
